apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskscale-worker
  namespace: monitoring
  labels:
    release: taskscale-monitoring
spec:
  namespaceSelector:
    matchNames:
      - taskscale
  selector:
    matchLabels:
      app: taskscale-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s